---
abstract: 'Helper library for writing WWW::TypePad apps'
author:
  - 'Benjamin Trott <ben@sixapart.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-TypePad-CmdLine
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Config::Tiny: 0
  File::HomeDir: 0
  WWW::TypePad: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/btrott/WWW-TypePad-CmdLine.git
version: 0.01
